cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: 2024.11.3
  ai_chat_mode: llm
  ai_image_mode: multiple
  author_name: Pr. Victor Maestri
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: kamal
  description: "Existe um prop\xF3sito para sua vida, e o fato de voc\xEA estar lendo\
    \ isto n\xE3o \xE9 obra do acaso ! Chega ! Chegou a hora de voc\xEA ser Livre\
    \ !"
  docker_setup: default
  domain_name: Livre.one
  email: contato@maestri.email
  enable_github_login: n
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: htmx
  github_username: MaestriGroup33
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: Livre.one | Seja Livre ! | Foi para a liberdade que Cristo nos libertou.
    (Gl5:1a NVT)
  project_slug: core
  python_package_manager: pip-tools
  standalone_front_end: vite
  stripe_payment_mode: checkout
  subscription_billing_model: per_unit
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_api_auth: y
  use_api_keys: y
  use_async_example: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_flowbite: y
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: y
  use_subscriptions: y
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: y
